### ISSUE TITLE
Installation - is there a set of versions of dependencies that work?

### ISSUE THREAD

**Issue by jmokland** [8d1h/IntersectionTheory#1]
I have tried on debian testing/osx 10.15.7/windows 10 all with julia-1.6.1 on x86_64 with no luck. The below error is from windows 10 with subsystem for linux and Ubuntu 20.04.

> ERROR: Unsatisfiable requirements detected for package Singular [bcd08a7b]:
>  Singular [bcd08a7b] log:
>  ├─possible versions are: 0.1.0-0.5.2 or uninstalled
>  ├─restricted to versions 0.5.2-0.5 by IntersectionTheory [6df59490], leaving only versions 0.5.2
>  │ └─IntersectionTheory [6df59490] log:
>  │   ├─possible versions are: 0.1.0 or uninstalled
>  │   └─IntersectionTheory [6df59490] is fixed to version 0.1.0
>  └─restricted by compatibility requirements with Nemo [2edaba10] to versions: uninstalled — no versions left
>    └─Nemo [2edaba10] log:
>      ├─possible versions are: 0.9.0-0.23.0 or uninstalled
>      └─restricted to versions 0.23 by IntersectionTheory [6df59490], leaving only versions 0.23.0
>        └─IntersectionTheory [6df59490] log: see above

**Comment by jieaosong** [comment]
Yeah sorry, I'm using a very recent version of Singular.jl so this doesn't work right away. Here is the work around:

You need to use the develop version of Singular.jl: type `]` to go to package manager and then
```
dev Singular
```
Then edit the file `~/.julia/dev/Singular/Project.toml` and change this line
```
libsingular_julia_jll = "~0.9.200"
```
to
```
libsingular_julia_jll = "~0.11.0"
```
(This is a very recent dependency issue in Singular.jl and should soon be fixed https://github.com/oscar-system/Singular.jl/pull/430)
Then try install again, which normally should work.

**Comment by jieaosong** [comment]
Hi, just for information: the dependency issue in Singular.jl has been fixed, so the above work-around is no longer needed.

Also, thank you for your interest in this project!
